### PR TITLE
Support additional test sourceSets.

### PR DESCRIPTION
**Pull request by Suvarov454**
Fix for https://github.com/bmuschko/gradle-clover-plugin/issues/11
Merged branch
https://github.com/bmuschko/gradle-clover-plugin/tree/refactoring into
trunk and finished implementation.
Example build.gradle stanza:
clover {
    additionalTestSourceSets << [
        srcDirs: sourceSets.integration.allSource.srcDirs,
        classesDir: sourceSets.integration.output.classesDir
    ]
}

### CODE REVIEW

**Comment by Alex-Vol** [comment]
I created a proper integration test for this PR. I am going to merge it and an add the integration test as a second commit.

**Comment by JeffQuandt** [comment]
Any idea when this/v2.1.0 is scheduled for release?

**Comment by Alex-Vol-SV** [comment]
This issue fix has been released in v2.1.0. The Gradle plugins repository has this new version already.

[Gradle Clover Plugin](https://plugins.gradle.org/plugin/com.bmuschko.clover)

**Comment by JeffQuandt** [comment]
Great. The latest release on GitHub shows 2.0.1.

**Comment by Alex-Vol-SV** [comment]
I will ask @bmuschko about this. We released 2.1.0 a few weeks now but the release process might have been changed. Perhaps we missed a step. Official releases can be found in the Gradle plugins repository at all times.

I am preparing an incremental 2.1.1 release in a week or two.

**Pull request merged**
